<?php
/**
 * @file
 */

use Drupal\pwa\manifestClass;

/**
 * Implements hook_page_attachments().
 * @param array $attachments
 */
function pwa_page_attachments(array &$attachments) {
    if (!\Drupal::currentUser()->hasPermission('access pwa')) {
        return;
    }
    $attachments['#attached']['library'][] = 'pwa/serviceworker';
    $attachments['#attached']['drupalSettings']['pwa'] = [
        'precache' => ['/', '/offline'],
    ];

    //Arno code
    $attachments['#attached']['html_head'][] = [[
        '#tag' => 'link',
        '#attributes' => [
            'rel' => 'manifest',
            'href' => '/manifest.json',
        ],
    ], 'manifest'];
    //todo: change theme collor to config
    $attachments['#attached']['html_head'][] = [[
        '#tag' => 'meta',
        '#attributes' => [
            'name' => 'theme-color',
            'content' => '#ffffff',
        ],
    ], 'meta_theme_color'];

}


